#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Aug 18 13:48:06 2020

@author: manish
"""


def Q79():
    # Read text file
    fhand = open('p079_keylog.txt', 'r')
    nums_after = [set() for _ in range(10)]


    #Create nums_after which is the primary data structure to solve this problem.
    for line in fhand:
        arr = [int(x) for x in line.strip()]
        nums_after[arr[0]].update([arr[1],arr[2]])
        nums_after[arr[1]].add(arr[2])

    #Extracting answer from nums_after
    b = set([i for i in range(10)])
    ans = ""
    while len(b) != 1:
        x = set(b)
        for i in range(10):
            x -= nums_after[i]
        b -= x
        for i in x:
            if len(nums_after[i]) != 0:
                ans += str(i)
                nums_after[i] = set()

    ans += str(b.pop())
    print("Shortest possible secret passcode:", ans)
    
if __name__ == '__main__':
    import time
    start_time = time.time()
    Q79()
    print("Program run time(in s): ", (time.time() - start_time)) 
