#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Sep 18 12:09:52 2020

@author: manish
"""

def Gf_arr(f):
    N = len(f)
    Gf = [None]*N
    Gf[1] = 0
    Gf[2] = 1
    for i in range(3, N):
        Gf[i] = Gf[i-1] + Gf[i-2]+ f[i-2]
    return Gf

def get_fib_series(n):
  f = [None, 1, 2]
  i = 2
  while True:
    x = f[i]+f[i-1]
    if x > n:
      return f
    else:
      f.append(x)
    i += 1
    
def G(n, f, Gf):
    i = 1
    if n==0: return 0
    while f[i]<=n:
        i+=1
    i = i -1
    return Gf[i] + (n-f[i]) + G(n-f[i],f, Gf)

def Q(n):
    f = get_fib_series(n)
    Gf = Gf_arr(f)
    ans = G(n - f[len(f)-1], f, Gf) + (n-f[len(f)-1]) + Gf[len(f)-1]
    print("The answer is:", ans)

if __name__ == '__main__':
    import time
    start_time = time.time()
    Q(10**17)
    print("Program run time(in s): ", (time.time() - start_time)) 